version: '3.3'

services:

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - discovery

  discovery:
    image: "consul:1.8"
#    ports:
#      - "8500:8500"

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile


  redis:
    image: "redis:latest"

  postgres-user-collections:
    image: "postgres:10"

  postgres-scores:
    image: "postgres:10"

  postgres-auth:
    image: "postgres:10"


  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - redis
      - postgres-auth

  cards_0:
    build:
      context: ./cards
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery

  cards_1:
    build:
      context: ./cards
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery

  user-collections:
    build:
      context: ./user-collections
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery
      - postgres-user-collections
      - auth
#    ports:
#      - "8600:8080"

  scores:
    build:
      context: ./scores
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery
      - postgres-scores






