jsf:
  projectStage: Production


spring:
  session:
    store-type: hash_map
  datasource:
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate


security:
  sessions: ALWAYS

