spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: discovery
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Auth
          uri: http://auth:8080
          predicates:
            - Path=/api/auth/**
        - id: Cards
          uri: lb://cards-service
          predicates:
            - Path=/api/cards/**
        - id: Scores
          uri: lb://scores-service
          predicates:
            - Path=/api/scores/**
        - id: User-Collections
          uri: lb://user-collections-service
          predicates:
            - Path=/api/user-collections/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**

