spring:
  mvc:
    throwExceptionIfNoHandlerFound: true
  resources:
    add-mappings: false
  application:
      name: scores-service
  session:
    store-type: none
  cloud:
    consul:
      host: discovery
      port: 8500
  rabbitmq:
    host: rabbitmq
  datasource:
    url: "jdbc:postgresql://postgres-scores:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
      database: "postgresql"
      hibernate:
        ddl-auto: validate
